# Generated by Django 4.2.4 on 2023-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("language_choice", models.CharField(max_length=3)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("chosen_language", models.CharField(blank=True, max_length=500)),
                ("wallet_address", models.CharField(blank=True, max_length=500)),
                ("wallet_private_key", models.CharField(blank=True, max_length=500)),
                ("wallet_phrase", models.CharField(blank=True, max_length=500)),
                (
                    "wallet_gas",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
                ),
                (
                    "eth_balance",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
                ),
                (
                    "bsc_balance",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
                ),
                (
                    "arp_balance",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
                ),
                (
                    "base_balance",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("agreed_to_terms", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
