# Generated by Django 4.2.4 on 2023-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="chosen_language",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="wallet_phrase",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="wallet_private_key",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
