# Generated by Django 4.2.4 on 2023-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_customuser_email_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ARB_added",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="BASE_added",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="BSC_added",
            field=models.BooleanField(default=False),
        ),
    ]
