# Generated by Django 4.2.4 on 2023-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_arb_added_customuser_base_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="arp_preset",
            field=models.CharField(
                choices=[
                    ("FAST", "FAST"),
                    ("SLOW", "SLOW"),
                    ("AVERAGE", "AVERAGE"),
                    ("MAX_SPEED", "MAX_SPEED"),
                ],
                default="AVERAGE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="base_preset",
            field=models.CharField(
                choices=[
                    ("FAST", "FAST"),
                    ("SLOW", "SLOW"),
                    ("AVERAGE", "AVERAGE"),
                    ("MAX_SPEED", "MAX_SPEED"),
                ],
                default="AVERAGE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bsc_preset",
            field=models.CharField(
                choices=[
                    ("FAST", "FAST"),
                    ("SLOW", "SLOW"),
                    ("AVERAGE", "AVERAGE"),
                    ("MAX_SPEED", "MAX_SPEED"),
                ],
                default="AVERAGE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="eth_preset",
            field=models.CharField(
                choices=[
                    ("FAST", "FAST"),
                    ("SLOW", "SLOW"),
                    ("AVERAGE", "AVERAGE"),
                    ("MAX_SPEED", "MAX_SPEED"),
                ],
                default="AVERAGE",
                max_length=15,
            ),
        ),
    ]
