# Generated by Django 4.2.4 on 2023-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_arp_preset_customuser_base_preset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="max_delta",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="max_gas",
            field=models.DecimalField(decimal_places=2, default=14.48, max_digits=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="slippage",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
    ]
