# Generated by Django 4.2.4 on 2023-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_max_delta_customuser_max_gas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auto_approve",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="auto_buy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="auto_sell",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="dupe_buy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sell_hi",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sell_hi_amount",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sell_lo",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sell_lo_amount",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
    ]
