# Generated by Django 4.2.4 on 2023-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_auto_approve_customuser_auto_buy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sell_hi",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sell_hi_amount",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sell_lo",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sell_lo_amount",
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=20),
        ),
    ]
