# Generated by Django 4.2.4 on 2023-09-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_max_gas"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="max_gas_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
