# Generated by Django 4.2.4 on 2023-09-15 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_copytradeaddresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="copytradeaddresses",
            name="chain",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="on",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="copytradeaddresses",
            name="contract_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="copytradeaddresses",
            name="name",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="copytradeaddresses",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy_trades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
