# Generated by Django 4.2.4 on 2023-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_copytradeaddresses_chain_copytradeaddresses_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="copytradeaddresses",
            name="amount",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="auto_buy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="copy_sell",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="gas_delta",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="max_buy_tax",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="max_sell_tax",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="sell_hi",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="sell_hi_amount",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="sell_lo",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="sell_lo_amount",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="slippage",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="copytradeaddresses",
            name="smart_slippage",
            field=models.BooleanField(default=True),
        ),
    ]
