# Generated by Django 4.2.4 on 2023-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_copytradeaddresses_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="copytradeaddresses",
            name="multi",
            field=models.BooleanField(default=False),
        ),
    ]
