# Generated by Django 4.2.4 on 2023-09-21 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_copytradeaddresses_multi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sniper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(blank=True, max_length=5)),
                ("contract_address", models.CharField(blank=True, max_length=500)),
                ("buy", models.BooleanField(default=True)),
                ("enable", models.BooleanField(default=True)),
                ("stop", models.BooleanField(default=False)),
                ("approve", models.BooleanField(default=True)),
                ("auto_sell", models.BooleanField(default=True)),
                ("buy_dip", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sniper",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
