# Generated by Django 4.2.4 on 2023-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_sniper"),
    ]

    operations = [
        migrations.AddField(
            model_name="sniper",
            name="auto",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sniper",
            name="block_delay",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name="sniper",
            name="eth",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name="sniper",
            name="liquidity",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sniper",
            name="method",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sniper",
            name="token",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=25),
        ),
    ]
