# Generated by Django 4.2.4 on 2023-09-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_sniper_auto_sniper_block_delay_sniper_eth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sniper",
            name="block_delay",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="eth",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="token",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
