# Generated by Django 4.2.4 on 2023-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_sniper_block_delay_alter_sniper_eth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sniper",
            name="multi",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="eth",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="token",
            field=models.DecimalField(decimal_places=6, default=10, max_digits=12),
        ),
    ]
