# Generated by Django 4.2.4 on 2023-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_sniper_multi_alter_sniper_eth_alter_sniper_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="sniper",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="auto",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="liquidity",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="method",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sniper",
            name="multi",
            field=models.BooleanField(default=False),
        ),
    ]
