# Generated by Django 4.2.4 on 2023-09-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0020_sniper_name_alter_sniper_auto_alter_sniper_liquidity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sniper",
            name="decimal",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="sniper",
            name="symbol",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
