# Generated by Django 4.2.4 on 2023-09-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_copytradetxhash_txhash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copytradetxhash',
            old_name='user_id_copy',
            new_name='user_id',
        ),
    ]
