# Generated by Django 4.2.4 on 2023-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_user_id_copy_copytradetxhash_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradetxhash',
            name='token_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
