# Generated by Django 4.2.4 on 2023-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_tradeaddress_txhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaddress',
            name='ammount_limit',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
    ]
