# Generated by Django 4.2.4 on 2023-09-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_tradeaddress_limit_alter_tradeaddress_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradetxhash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=500)),
                ('txhash', models.CharField(blank=True, max_length=500)),
                ('bot_name', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('token_address', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
